In [118]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [119]:
df = pd.read_csv('Housing.csv')

In [120]:
y = df.iloc[:,0].values


In [121]:
X = df.iloc[:,1:4].values
X

array([[7420,    4,    2],
       [8960,    4,    4],
       [9960,    3,    2],
       ...,
       [3620,    2,    1],
       [2910,    3,    1],
       [3850,    3,    1]])

In [122]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [123]:
print(df.isnull().sum())

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64


In [124]:
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3,random_state = 0)

In [125]:
X_train

array([[4500,    3,    1],
       [3990,    3,    1],
       [4320,    3,    1],
       ...,
       [5750,    3,    2],
       [3600,    3,    1],
       [6600,    3,    1]])

In [126]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [127]:
y_train = sc.fit_transform(y_train.reshape(-1,1))
y_test= sc.transform(y_test.reshape(-1,1))


In [128]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [129]:
ypred = model.predict(X_test)

In [130]:
print(sc.inverse_transform(ypred))

[[ 3959098.84071357]
 [ 6297401.95435691]
 [ 4242278.46828465]
 [ 7279069.5626356 ]
 [ 4325492.10222214]
 [ 6334387.60285959]
 [ 3896688.61526046]
 [ 3742743.39247611]
 [ 3248201.13470382]
 [ 7944824.69173356]
 [ 6696620.18267128]
 [ 3942456.11392608]
 [ 3730261.34738549]
 [ 4816199.27026967]
 [ 4784994.15754311]
 [ 3305871.81430431]
 [ 3825703.75422996]
 [ 4799556.54348217]
 [ 3584637.48799489]
 [ 3659276.48635499]
 [ 7083310.30829696]
 [ 6375994.41982833]
 [ 4375167.010401  ]
 [ 3002142.05043249]
 [ 4965983.81135714]
 [ 5002969.45985983]
 [ 5207303.34977585]
 [ 4658093.36578845]
 [ 6462908.24869351]
 [ 4965983.81135714]
 [ 3617669.66938625]
 [ 3241381.24800276]
 [ 5789798.78733825]
 [ 3467885.12829878]
 [ 3592958.85138864]
 [ 4466448.7355486 ]
 [ 5299091.61929071]
 [ 3558009.12513489]
 [ 2714548.46898091]
 [ 3199774.43103402]
 [ 7228934.16768756]
 [ 6655013.36570254]
 [ 6105550.10953151]
 [ 4581120.75439627]
 [ 3759386.11926361]
 [ 6188763.74346899]
 [ 4025669.74786356]
 [ 3467885.12

In [131]:
print(np.concatenate(sc.inverse_transform(ypred)),sc.inverse_transform(y_test))

[ 3959098.84071357  6297401.95435691  4242278.46828465  7279069.5626356
  4325492.10222214  6334387.60285959  3896688.61526046  3742743.39247611
  3248201.13470382  7944824.69173356  6696620.18267128  3942456.11392608
  3730261.34738549  4816199.27026967  4784994.15754311  3305871.81430431
  3825703.75422996  4799556.54348217  3584637.48799489  3659276.48635499
  7083310.30829696  6375994.41982833  4375167.010401    3002142.05043249
  4965983.81135714  5002969.45985983  5207303.34977585  4658093.36578845
  6462908.24869351  4965983.81135714  3617669.66938625  3241381.24800276
  5789798.78733825  3467885.12829878  3592958.85138864  4466448.7355486
  5299091.61929071  3558009.12513489  2714548.46898091  3199774.43103402
  7228934.16768756  6655013.36570254  6105550.10953151  4581120.75439627
  3759386.11926361  6188763.74346899  4025669.74786356  3467885.12829878
  3978237.97651919  4666414.7291822   4308596.10325101  8222342.16091507
  2981338.64194812  3388832.17605817  4741306.9997259

In [132]:
from sklearn.metrics import r2_score

In [133]:
print(r2_score(y_test,ypred)*100)

50.41100166137953
